#!/bin/bash

pacman_packages=(
  "ardour"
  "calibre"
  "dosfstools"
  "eza"
  "flatpak"
  "github-cli"
  "lazydocker"
  "lazygit"
  "libfdk-aac"
  "neovim"
  "steam"
  "syncthing"
  "tailscale"
  "ttf-jetbrains-mono-nerd"
  "v4l2loopback-dkms"
  "wezterm"
  "zsh-autosuggestions"
  "zsh"
)

yay_packages=(
  "lazyssh-bin"
  "neural-amp-modeler-lv2-git"
  "obs-studio-git"
  "vscodium-bin"
  "libation"
)

flatpak_packages=(
  "com.bitwarden.desktop"
  "com.brave.Browser"
  "com.discordapp.Discord"
  "com.github.IsmaelMartinez.teams_for_linux"
  "com.heroicgameslauncher.hgl"
  "com.makemkv.MakeMKV"
  "com.mattjakeman.ExtensionManager"
  "com.todoist.Todoist"
  "fr.handbrake.ghb"
  "md.obsidian.Obsidian"
  "org.kde.ktorrent"
  "org.onlyoffice.desktopeditors"
  "org.signal.Signal"
  "org.videolan.VLC"
  "us.zoom.Zoom"
)

custom_packages=(
  "starship"
)
